### ISSUE TITLE
Feat/128- Volunteer ageda unsubscribe

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#128]
**Is your feature request related to a problem? Please describe.**
Not applicable

**Describe the solution you'd like**
The volunteer can have the option of unsubscribe of the event if he wants
**Describe alternatives you've considered**

**Additional context**

**Comment by manbarjim2** [comment]
Would it be correct for this to be on the events you attend screen?, a button to stop attending.

**Comment by marnunrey2** [comment]
> Would it be correct for this to be on the events you attend screen?, a button to stop attending.

I would say so, yes. There are other screens that uses the trash Icon from material design, so you could use it to add it in the asistencia boxes from each event and show a dialog window making sure that his/her decision is to stop attending. Also, make sure that, in the asistencia screen, it does not show any event that has already passed

**Comment by claugp06** [comment]
> > Would it be correct for this to be on the events you attend screen?, a button to stop attending.
> 
> I would say so, yes. There are other screens that uses the trash Icon from material design, so you could use it to add it in the asistencia boxes from each event and show a dialog window making sure that his/her decision is to stop attending. Also, make sure that, in the asistencia screen, it does not show any event that has already passed

Yes, I agree with Maria that seems like the best implementation idea for it

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/vuYYAHN6SI/estimate/7) in Frontend S2 W8

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
