### ISSUE TITLE
Fix/145- about us video and dosier

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#145]
**Describe the bug**
The video and dosier should be include in the screen and it is not
**To Reproduce**
1. Go to 'localhost:3000'
2. Click on '.About us...'
3. Scroll down 

**Expected behavior**
The video and dosier should be include it at it is their actual web page
**Screenshots**

**Additional context**
If you can, fix also that the log in can be done with the enter button

**Comment by marnunrey2** [comment]
This issue will not be finished in this sprint due to the delay of the NGO to give us the dosier needed to include in the 'about us' page

**Comment by pabpercab1** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/8) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
