### ISSUE TITLE
Feature/161-Payment system

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#161]
**Is your feature request related to a problem? Please describe.**
Not applicable
**Describe the solution you'd like**
The payment system implementation has already been made by the backend side. Now, it is has to be implement it in the frontend side
**Describe alternatives you've considered**
Not applicable
**Additional context**
Any doubts about it asked Romalde from the back because he is the one that implement it and could have more detail of it. Also, comment that it is implement by using Stripe

**Comment by fracalrod3** [comment]
Excuse me, would you be so kind to tell me how can I access the payment through the Back-End's api? i can't seem to find it, are we talking about donations' Front-End?

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/21) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
