### ISSUE TITLE
Fix/162- Volunteers calendar

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#162]
**Describe the bug**
The volunteers should be able to sign in for events, lesson events (the ones that belongs to a speciic class) and class they can attend
**Expected behavior**
Right now you can just add yourself to events but the possibilities mentioned above should be also consider and implement it.
**Screenshots**
Not applocable

**Comment by manbarjim2** [comment]
It is not entirely clear to me what you mean by the ones that belong to a speciic class

**Comment by claugp06** [comment]
> It is not entirely clear to me what you mean by the ones that belong to a speciic class

Hey, lesson events are a type of events which belong to a specific class ( I described it like that so you could see the difference in the diagram of the database)

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/15) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
