### ISSUE TITLE
Fix/163-Volunteers attendance

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#163]
**Describe the bug**
Instead of a Toast message an alert message it is shown. Also all the different type of activities that a volunteer can attend should be shown by indicating the name and what type of activity it is: event, lesson event or a lesson
**Expected behavior**
Volunteer can sign in for different type of activities and the option of showing all of this should be include it in the attendence screen. Right now only the event endpoint it is been used.

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/29) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
