### ISSUE TITLE
Feature/165-Recurring donations

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#165]
**Is your feature request related to a problem? Please describe.**
Not applicable
**Describe the solution you'd like**
The register of a partner role needs to be implement it. If you want to do more than one time donations, the partner register screen should be done.
After the register it is done, the partner should be navigate to partner data personal to finish the register steps
**Additional context**
More information can be seen in figma

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/3) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
