### ISSUE TITLE
Feature/170- Family calendars

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#170]
**Is your feature request related to a problem? Please describe.**
Not applicable

**Describe the solution you'd like**
The family should be able to access a calendar in which they can see the classes, events or lesson events of their kids.
A calendar should be include it with the previous information.
**Describe alternatives you've considered**
Not applcable

**Additional context**
Use the mockups and to see how a calendar can be implement have a look to volunteers were there is an example

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/25) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
