### ISSUE TITLE
Feature/171-Registration of families

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#171]
**Is your feature request related to a problem? Please describe.**
Not applicable

**Describe the solution you'd like**
Once an user has register and has the role as family, it should be redirect to the forms corresponding to the family. Two forms should be done one with the kids info and another with family data.
**Additional context**
Reuse styles and components in the case it is possible and rembember that the mock ups can be used as inspirations

**Comment by manbarjim2** [comment]
Before filling out the form, the user should accept their account in the email, when should this form appear?

**Comment by manbarjim2** [comment]
What would be the difference between the kid's form and the family form?

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/26) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
