### ISSUE TITLE
Fix/172- Feedback pilot users

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#172]
**Describe the bug**
There is several bugs that have been detect by the pilot users and the needed implementation to fix this will be done

**Expected behavior**
Some of this errors include the validations and errors messages.
Changes to be done:
- check spelling mistakes
- change the name of the tab to manos abiertas
- Footer phone number more visibles
- Use interactive maps for "Donde estamos"
- Forms of admin better message errors
- Edit/delete toast success 
- Header smaller volunteers. 
- Message of not requests in volunteers admin screen
- Educators errors messages more detail
- Change add educator to a button
- Time field only time not day time as now
- Error message in partenrs
- Lesson messages error
- When editing an event the changes should appear inmeddiatley
- Calendar style
- Suggestion, not line jump
- Grammatical error in suggestions error messages

**Comment by claugp06** [comment]
After reading the Feedback ad considering the option. I think it is better to leave the creation of meetings as it is because if not in that screen to button will appear one for export and other for creation and the screen will love a bit too crowed

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/17) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
