### ISSUE TITLE
Feat/191-Partners membership

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#191]
**Is your feature request related to a problem? Please describe.**
Not applicable
**Describe the solution you'd like**
The partners should be able to modify the quantity they donated, to update their membership and cancel their membership.
**Describe alternatives you've considered**
Not applicable 
**Additional context**
Use the mock ups in figma https://www.figma.com/file/uCBbvfz4BH6ooGEeeFRyZO/ISPP?type=design&node-id=150-4178&mode=design&t=uV53ZwfWd1D0fFcI-0 as inspiration, make sure that the design of the screen are resposive for different screen sizes and any doubt do not hestiate to ask. The profile ad update profile screen can be re-use for the partners part to save time

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/wf7zEDl7Zm/estimate/2) in Frontend S3 v2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
