### ISSUE TITLE
Fix/233-Evaluation Educator

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#233]
**Describe the bug**
When you are log in as educator, the daily and yearly evaluation screen shows a list of all the kids that that educator gives class to. An educator can have more than one class, so some of the kids belongs to one and others to other class.
It has been decided to change the mentioned screens to have the evaluation separated by classes instead of having the list of the kids without any type of filter.

**To Reproduce**
1. Go to 'Log in.’
2. Enter credentials of an educator 
3. Go to “Evaluación diaria” / “ Evaluación anual”
**Expected behavior**
To maintain a more organized way of evaluating the kids, the idea of showing the content dividing it by classes have been decided. 
For this purpose, the creation of a dropdown to select the class and depending on the class chosen the corresponding students are given and evaluated.
Also, in this screen the information regarding the family and the student it is shown in English and should be shown in Spanish.
**Additional context**
Any idea for representing in a better visual way the evaluation divided by classes it is welcomed. The one given is just a proposal.
PACO FRAN,SERGIO,IVAN
**Describe the bug**
After comparing the web page, we are developing with the one that the NGO has at the moment, we have realized that the screen corresponding to “organization” is missing and should be added.

**To Reproduce**
1. Go to 'Asociación' 
2. You will see the dropdown with the available options
3. “Organización” does not appear

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/wmglGeTQBi/estimate/4) in Front PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
