### ISSUE TITLE
Fix/237-Volunteer Calendar

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#237]
**Describe the bug**
The volunteer’s calendar should also show the classes because volunteers should be able to sign up for them and at the moment they are not shown.

**To Reproduce**
1. Go to 'Log in.' 
2. Sign up with a volunteer account
3. Go to calendar

**Expected behavior**
Volunteers can sign up for: lessons, lessons events and events. At the moment, the only two last ones are shown in the calendar, and it is a need and a requirement of the NGO that lessons also appears on it and volunteers can sign up for it .
**Additional context**
There is a schedule endpoint that shows the times that a class happens and this time should be shown also in the calendar. Maybe is better that it is show on the details of the class but feel free to adjust as you better think could fit better.

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/wmglGeTQBi/estimate/6) in Front PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
