### ISSUE TITLE
Fix/238- Delete confirmation message 

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#238]
**Describe the bug**
After the feedback from the pilot users and reviewing the web app once it was deployed, the necessity of adding a message before deleting is a must. For that reason in  this issue all the delete action that are perform (they are located on the admin screen) should have a confirmation message.
**Expected behavior**
Before deleting something a message of confirmation should be displayed to assure that the action it is done because the user wants and not a mistake.
**Additional context**
The screens you should check are volunteers, educators and suggestions and if you have any doubt about how the message should be look on the “Borrar cuenta” on the profile that does have a confirmation message before deleting. Any other action that you see that contemplates a delete action, please check if it has a confirmation message ( I might have forgotten some screen)

**Comment by pabpercab1** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/wmglGeTQBi/estimate/7) in Front PPL

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
