### ISSUE TITLE
Feature/7-Admin screen- volunteers and educators

### ISSUE THREAD

**Issue by MRomalde** [ISPP-G5/NexONG_Frontend#7]

**Comment by claugp06** [comment]
The main objective with this issue it is that the users log in as administrators can see the volunteers and educators of the NGO as well as accepting the new requests.
In order to complete it, use the data provided by the backend mora specifically by the partners API.

**Comment by pabpercab1** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/v4oCWatSG4/estimate/15) in Frontend S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
