### ISSUE TITLE
Feature/8-AdminScreen Partners

### ISSUE THREAD

**Issue by MRomalde** [ISPP-G5/NexONG_Frontend#8]

**Comment by claugp06** [comment]
The main objective with this issue it is that the users log in as administrators can see the partners of the NGO as well as accepting the new requests.
In order to complete it, use the data provided by the backend mora specifically by the partners API.

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/v4oCWatSG4/estimate/14) in Frontend S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
