### ISSUE TITLE
Feature/81-Navbar suggestions

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#81]
**Describe the solution you'd like**
The aim of this issue it is to create the suggestions screen. A form containing the name in a input box (not mandatory) and a input box for comments so that suggestions can be done.
The information inside the form of suggestion should reach the API of suggestions.
**Describe alternatives you've considered**
Not applicable

**Additional context**
Not applicable

**Comment by FranciscoRossoR** [comment]
Page view created, waiting for the corresponding backend tasks to be ready so I can continue with the data submission.

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/v4oCWatSG4/estimate/12) in Frontend S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
