### ISSUE TITLE
Feature/87-Volunteers Formation

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#87]
**Is your feature request related to a problem? Please describe.**
Not applicable
**Describe the solution you'd like**
The screen of volunteers formation should be access once the form of the volunteers it is completed. This screen should show the 3 different videos that the applicant for volunteer should watch.
Also create the second form needed for the volunteers and check if the first one works.

**Describe alternatives you've considered**
Not applicable
**Additional context**
Any doubt with the design have a look on the mock ups.

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/v4oCWatSG4/estimate/6) in Frontend S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/28) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
