### ISSUE TITLE
Feature/89-Volunteers Documentation

### ISSUE THREAD

**Issue by claugp06** [ISPP-G5/NexONG_Frontend#89]
**Is your feature request related to a problem? Please describe.**
Once the volunteers have watched the 3 videos, it should access the Documentation screen.
**Describe the solution you'd like**
This screeen should show the documents needed to be completed by the applicant and once it is completed to send it to the backend.
**Describe alternatives you've considered**

**Additional context**

**Comment by pabpercab1** [comment]
**Story Points: 13**
  [See the discussion](https://action.parabol.co/meet/v4oCWatSG4/estimate/4) in Frontend S2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by pabpercab1** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/vS6Bu8mLF6/estimate/6) in Frontend S3

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
